export const jobSkills = [
    // "React Native",
    // "Flutter",
    // "Android",
    // "Java",
    // "Kotlin",
    // "iOS",
    // "Swift",
    // "Objective-C",
    // "Unity",
    // "Unreal",
    // "Cocos2d",
    "Blockchain",
    "Defi",
    "NFT",
    "Bitcoin",
    "Frontend",
    "Backend",
    "React",
    "Node",
    "Full Stack",
    "Golang",
    "Rust",
    "Solidity",
    "JavaScript",
    "TypeScript"
]
  
export const hireSkills = [
    // "React Native",
    // "Flutter",
    // "Android",
    // "Java",
    // "Kotlin",
    // "iOS",
    // "Swift",
    // "Objective-C",
    // "Unity",
    // "Unreal",
    // "Cocos2d",
    // "Xamarin",
    "Blockchain",
    "Defi",
    "NFT",
    "Bitcoin",
    "Frontend",
    "Backend",
    "React",
    "Node",
    "Full Stack",
    "Golang",
    "Rust",
    "Solidity",
    "JavaScript",
    "TypeScript"
  ]